#!/usr/bin/env node

/**
 * Module dependencies.
 */
const httpType = 'http';
var app = require('./app');
var debug = require('debug')('FlightClub:server');
var https = require('https');
var http = require('http');
const fs = require("fs");
var log = require('debug-level').log('www');

/**
 * Get port from environment and store in Express.
 */

var env = require('dotenv').config();
/*  log.info(env); */
var port = normalizePort(process.env.PORT || '3003');
app.set('port', port);

/**
 * Create HTTP server.
 */
var server;
if (httpType === 'https') {
  server = https.createServer(
    {
      key: fs.readFileSync("key.pem"),
      cert: fs.readFileSync("cert.pem"),
    },
    app);
    log.log(`server https ${server}`);
}
else {
  server = http.createServer(app);
  log.log(`server http ${server}`);
}
/**
 * Listen on provided port, on all network interfaces.
 */
server.on('error', onError);
server.on('listening', onListening);
server.listen(port, process.env.ADDRESS);


/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

/* function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
 */
function onListening() {

  log.log(`Listening on ${server.address().address}::${server.address().port}`);
}