export  enum URLS{
    BACKEND_URL = "http://localhost:3002",
    LOGIN = "api/login",
    CHANGE_PASSWORD = "api/change_password",
    RESERVATION = 'api/reservation',
    RESERVATION_DELETE = 'api/reservation/delete',
    RESERVATION_CREATE = 'api/reservation/create',
    RESERVATION_UPDATE = 'api/reservation/update',
    MEMBERS = 'api/members',
    RESET = 'api/reset_password',
    MEMBER_DETAIL = 'api/members/detail',
    DEVICES = 'api/devices',
    FLIGHT = 'api/flight',
    CLUB_NOTICE = 'api/club_notice',
    CLUB_NOTICE_UPDATE ='api/club_notice/update',
    CLUB_NOTICE_DELETE ='api/club_notice/delete',
    CLUB_NOTICE_CREATE ='api/club_notice/create',
    DEVICE_TYPES = 'api/deviceTypes',
    DEVICE_TYPES_DETAILES = 'api/deviceTypes',
    DEVICE_TYPES_DELETE = 'api/deviceTypes',
    DEVICE_TYPES_UPDATE = 'api/deviceTypes/update',
    DEVICE_TYPES_CREATE = 'api/deviceTypes/create',
    
}